version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKERHUB_PASS" | docker login -u "jeongukjae" --password-stdin
      - run: |
          for dockerfile in `find . -name "*Dockerfile" | sort` ; do
            image_name_and_tag=`echo $dockerfile | sed 's|\/images\/|:|g' | \
              sed 's|\.\/||g' | \
              sed 's|\/|-|g' | \
              sed 's|^|jeongukjae\/|g' | \
              sed 's|\.Dockerfile||'`
            echo "build $image_name_and_tag"
            docker build --quiet -t $image_name_and_tag -f $dockerfile `dirname $dockerfile`
            docker push $image_name_and_tag
          done

