version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    parallelism: 4
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "$DOCKERHUB_PASS" | docker login -u "jeongukjae" --password-stdin
      - run: |
          DOCKER_FILES_TO_BUILD=$(circleci tests glob "**/*.Dockerfile" | circleci tests split)
          for dockerfile in $DOCKER_FILES_TO_BUILD ; do
            image_name_and_tag=`echo $dockerfile | sed 's|\/images\/|:|g' | \
              sed 's|\.\/||g' | \
              sed 's|\/|-|g' | \
              sed 's|^|jeongukjae\/|g' | \
              sed 's|\.Dockerfile||'`
            echo "build $image_name_and_tag"
            docker build --quiet -t $image_name_and_tag -f $dockerfile `dirname $dockerfile`
            docker push $image_name_and_tag
            docker rmi $image_name_and_tag
          done

